# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Spring Configuration
spring:
  # Jackson JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    time-zone: UTC
    default-property-inclusion: non_null
  
  # JPA Configuration
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

# SpringDoc API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method