spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_AUTH_SERVER_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT_ID}
  credentials: 
    secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true

# Application specific settings
app:
  cors:
    allowed-origins: ${FRONTEND_APP_URL},http://localhost:3000

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers # Expose health and info endpoints
  endpoint:
    health:
      probes:
        enabled: true # Enable Kubernetes probes