spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_AUTH_SERVER_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

# Disable Keycloak for development
keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: resource-management
  resource: resource-management-app
  credentials:
    secret: dummy-secret
  use-resource-role-mappings: true
  bearer-only: true

# Application specific settings
app:
  cors:
    allowed-origins: ${FRONTEND_APP_URL},http://localhost:3000
  # Dev settings
  security:
    dev-mode: true
    admin-username: admin
    admin-password: admin