name: CD - Update Helm Chart with New Backend Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI - Build and Push Docker Images]
    types:
      - completed

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: prognose-backend-version

      - name: Read version
        id: read_version
        run: |
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Checkout Helm chart repository
        uses: actions/checkout@v4
        with:
          repository: giovannimirarchi420/prognose-helm-chart
          token: ${{ secrets.CHART_REPO_TOKEN }}
          path: helm-chart-repo

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update backend image tag in values.yaml
        run: |
          cd helm-chart-repo
          CURRENT_TAG=$(yq eval ".be.image.tag" values.yaml)
          if [[ "$CURRENT_TAG" =~ -([a-zA-Z]+)$ ]]; then
            DB_SUFFIX="-${BASH_REMATCH[1]}"
          else
            DB_SUFFIX="-postgres"
          fi
          NEW_TAG="${{ env.version }}${DB_SUFFIX}"
          yq eval ".be.image.tag = \"${NEW_TAG}\"" -i values.yaml

      - name: Commit and push Helm chart changes
        run: |
          cd helm-chart-repo
          if git diff --quiet; then
            echo "No changes detected in values.yaml"
            exit 0
          fi
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add values.yaml
          git commit -m "chore: update Backend image tag to ${{ env.version }}"
          git push
